const EXTRA_LEAVES = Object.freeze([
  Object.freeze({ label: "readme", parent: "guide", family: "repo", secondary: true, description: "README changes." }),
  Object.freeze({ label: "changelog", parent: "reference", family: "repo", secondary: true, description: "CHANGELOG changes." }),
  Object.freeze({ label: "pull template", parent: "template", family: "repo", secondary: true, description: "Pull request template changes.", legacyMatches: ["github"] }),
  Object.freeze({ label: "dependabot", parent: "manifest", family: "repo", secondary: true, description: "Dependabot configuration changes.", legacyMatches: ["dependencies", "security"] }),
  Object.freeze({ label: "dockerfile", parent: "build job", family: "pipeline", secondary: true, description: "Dockerfile changes.", legacyMatches: ["docker"] }),
  Object.freeze({ label: "compose", parent: "deploy job", family: "pipeline", secondary: true, description: "Compose file changes.", legacyMatches: ["docker"] }),
  Object.freeze({ label: "artifact upload", parent: "build job", family: "pipeline", secondary: true, description: "Artifact upload changes." }),
  Object.freeze({ label: "cache restore", parent: "build job", family: "pipeline", secondary: true, description: "Cache restore changes." }),
  Object.freeze({ label: "smoke test", parent: "test job", family: "pipeline", secondary: true, description: "Smoke test changes.", legacyMatches: ["test"] }),
  Object.freeze({ label: "branch filter", parent: "workflow file", family: "pipeline", secondary: true, description: "Branch filter changes.", legacyMatches: ["workflow"] }),
  Object.freeze({ label: "cuda", parent: "python", family: "runtime", releaseRelevant: true, description: "CUDA support changes.", legacyMatches: ["runtime"] }),
  Object.freeze({ label: "gpu memory", parent: "cuda", family: "runtime", releaseRelevant: true, description: "GPU memory changes." }),
  Object.freeze({ label: "kernel launch", parent: "cuda", family: "runtime", releaseRelevant: true, description: "Kernel launch changes." }),
  Object.freeze({ label: "seed data", parent: "migration file", family: "data", releaseRelevant: true, description: "Seed data changes.", legacyMatches: ["database", "migration"] }),
  Object.freeze({ label: "table rename", parent: "migration file", family: "data", releaseRelevant: true, description: "Table rename changes.", legacyMatches: ["migration", "compatibility"] }),
  Object.freeze({ label: "index ddl", parent: "query", family: "data", releaseRelevant: true, description: "Index DDL changes.", legacyMatches: ["database"] }),
  Object.freeze({ label: "db trigger", parent: "query", family: "data", releaseRelevant: true, description: "Database trigger changes.", legacyMatches: ["database"] }),
  Object.freeze({ label: "partition key", parent: "query", family: "data", releaseRelevant: true, description: "Partition key strategy changes.", legacyMatches: ["database"] }),
  Object.freeze({ label: "read replica", parent: "query", family: "data", releaseRelevant: true, description: "Read replica usage changes.", legacyMatches: ["database"] }),
  Object.freeze({ label: "retry budget", parent: "process", family: "runtime", releaseRelevant: true, description: "Retry budget changes." }),
  Object.freeze({ label: "worker pool", parent: "process", family: "runtime", releaseRelevant: true, description: "Worker pool behavior changes." }),
  Object.freeze({ label: "subprocess io", parent: "process", family: "runtime", releaseRelevant: true, description: "Subprocess IO behavior changes." }),
  Object.freeze({ label: "daemon mode", parent: "process", family: "runtime", releaseRelevant: true, description: "Daemon mode behavior changes." }),
  Object.freeze({ label: "path normalization", parent: "filesystem", family: "runtime", releaseRelevant: true, description: "Path normalization changes." }),
  Object.freeze({ label: "temp directory", parent: "filesystem", family: "runtime", releaseRelevant: true, description: "Temporary directory handling changes." }),
  Object.freeze({ label: "atomic write", parent: "filesystem", family: "runtime", releaseRelevant: true, description: "Atomic write behavior changes." }),
  Object.freeze({ label: "symlink safety", parent: "filesystem", family: "runtime", releaseRelevant: true, description: "Symlink safety changes." }),
  Object.freeze({ label: "http timeout", parent: "route", family: "api", releaseRelevant: true, description: "HTTP timeout handling changes." }),
  Object.freeze({ label: "pagination", parent: "route", family: "api", releaseRelevant: true, description: "Pagination contract changes." }),
  Object.freeze({ label: "idempotency key", parent: "request body", family: "api", releaseRelevant: true, description: "Idempotency key behavior changes." }),
  Object.freeze({ label: "status code", parent: "response body", family: "api", releaseRelevant: true, description: "HTTP status code contract changes.", versionBump: "major" }),
  Object.freeze({ label: "partial response", parent: "response body", family: "api", releaseRelevant: true, description: "Partial response support changes." }),
  Object.freeze({ label: "error code", parent: "error payload", family: "api", releaseRelevant: true, description: "Error code schema changes.", versionBump: "major" }),
  Object.freeze({ label: "auth header", parent: "token", family: "api", releaseRelevant: true, description: "Authorization header handling changes.", legacyMatches: ["security"] }),
  Object.freeze({ label: "key rotation", parent: "api key", family: "api", releaseRelevant: true, description: "API key rotation changes.", legacyMatches: ["security"] }),
  Object.freeze({ label: "scope defaults", parent: "oauth scope", family: "api", releaseRelevant: true, description: "Default OAuth scope changes." }),
  Object.freeze({ label: "permission inheritance", parent: "permission", family: "api", releaseRelevant: true, description: "Permission inheritance changes.", legacyMatches: ["security"] }),
  Object.freeze({ label: "audit trail", parent: "security posture", family: "api", releaseRelevant: true, description: "Security audit trail changes.", legacyMatches: ["security"] }),
  Object.freeze({ label: "incident response", parent: "security posture", family: "api", releaseRelevant: true, description: "Incident response workflow changes.", legacyMatches: ["security"] }),
  Object.freeze({ label: "sast", parent: "security scan", family: "pipeline", secondary: true, description: "Static analysis scan changes.", legacyMatches: ["security", "ci"] }),
  Object.freeze({ label: "sbom", parent: "security scan", family: "pipeline", secondary: true, description: "SBOM generation changes.", legacyMatches: ["security", "supply-chain"] }),
  Object.freeze({ label: "provenance", parent: "security scan", family: "pipeline", secondary: true, description: "Build provenance attestation changes.", legacyMatches: ["security", "supply-chain"] }),
  Object.freeze({ label: "canary deploy", parent: "staging deploy", family: "pipeline", secondary: true, description: "Canary deployment changes." }),
  Object.freeze({ label: "blue green", parent: "prod deploy", family: "pipeline", secondary: true, description: "Blue/green deployment changes." }),
  Object.freeze({ label: "release freeze", parent: "release gate", family: "pipeline", secondary: true, description: "Release freeze gate changes." }),
  Object.freeze({ label: "runner image", parent: "workflow file", family: "pipeline", secondary: true, description: "CI runner image changes." }),
  Object.freeze({ label: "self hosted runner", parent: "workflow file", family: "pipeline", secondary: true, description: "Self-hosted runner changes." }),
  Object.freeze({ label: "flaky quarantine", parent: "test job", family: "pipeline", secondary: true, description: "Flaky test quarantine changes.", legacyMatches: ["test"] }),
  Object.freeze({ label: "snapshot baseline", parent: "test fixture", family: "pipeline", secondary: true, description: "Snapshot baseline updates.", legacyMatches: ["test"] }),
  Object.freeze({ label: "abi compatibility", parent: "shared lib", family: "runtime", releaseRelevant: true, description: "ABI compatibility changes.", legacyMatches: ["compatibility"] }),
  Object.freeze({ label: "thread affinity", parent: "kernel launch", family: "runtime", releaseRelevant: true, description: "Thread affinity changes." }),
  Object.freeze({ label: "stream sync", parent: "kernel launch", family: "runtime", releaseRelevant: true, description: "CUDA stream synchronization changes." }),
  Object.freeze({ label: "memory pool", parent: "gpu memory", family: "runtime", releaseRelevant: true, description: "GPU memory pool changes." }),
  Object.freeze({ label: "manifest lock", parent: "package manifest", family: "repo", secondary: true, description: "Manifest lock and pinning changes.", legacyMatches: ["dependencies"] }),
  Object.freeze({ label: "extras group", parent: "dependency group", family: "repo", secondary: true, releaseRelevant: true, description: "Optional extras group changes.", legacyMatches: ["dependencies"] }),
  Object.freeze({ label: "build backend", parent: "pyproject", family: "repo", secondary: true, releaseRelevant: true, description: "Python build backend changes.", legacyMatches: ["packaging"] }),
  Object.freeze({ label: "entry point", parent: "package metadata", family: "pipeline", secondary: true, releaseRelevant: true, description: "Entry-point command changes.", legacyMatches: ["packaging"] }),
  Object.freeze({ label: "artifact signature", parent: "artifact upload", family: "pipeline", secondary: true, description: "Artifact signing changes.", legacyMatches: ["security", "supply-chain"] }),
  Object.freeze({ label: "cache key", parent: "cache restore", family: "pipeline", secondary: true, description: "Build cache key changes." }),
  Object.freeze({ label: "cache ttl", parent: "cache restore", family: "pipeline", secondary: true, description: "Build cache TTL changes." }),
  Object.freeze({ label: "release channel", parent: "release flow", family: "pipeline", secondary: true, description: "Release channel routing changes." }),
  Object.freeze({ label: "hotfix lane", parent: "release flow", family: "pipeline", secondary: true, description: "Hotfix lane changes." }),
  Object.freeze({ label: "contributing guide", parent: "guide", family: "repo", secondary: true, description: "Contributing guide changes." }),
  Object.freeze({ label: "security policy doc", parent: "reference", family: "repo", secondary: true, description: "Security policy documentation changes.", legacyMatches: ["policy", "security"] }),
  Object.freeze({ label: "deprecation notice", parent: "release note", family: "api", secondary: true, description: "Deprecation notice changes.", legacyMatches: ["deprecation"] }),
  Object.freeze({ label: "upgrade note", parent: "migration doc", family: "repo", secondary: true, description: "Upgrade note changes.", legacyMatches: ["migration"] }),
  Object.freeze({ label: "compat matrix", parent: "support matrix", family: "runtime", releaseRelevant: true, description: "Compatibility matrix updates.", legacyMatches: ["compatibility"] }),
  Object.freeze({ label: "platform gate", parent: "architecture", family: "runtime", releaseRelevant: true, description: "Platform gating logic changes." }),
  Object.freeze({ label: "timezone default", parent: "timezone", family: "runtime", releaseRelevant: true, description: "Timezone default behavior changes." }),
  Object.freeze({ label: "locale fallback", parent: "locale", family: "runtime", releaseRelevant: true, description: "Locale fallback changes." }),
  Object.freeze({ label: "session ttl", parent: "session", family: "api", releaseRelevant: true, description: "Session TTL changes.", legacyMatches: ["security"] }),
  Object.freeze({ label: "cookie flags", parent: "cookie", family: "api", releaseRelevant: true, description: "Cookie security flag changes.", legacyMatches: ["security"] }),
  Object.freeze({ label: "request tracing", parent: "route", family: "api", releaseRelevant: true, description: "Request tracing behavior changes.", legacyMatches: ["observability"] }),
  Object.freeze({ label: "schema migration guard", parent: "migration file", family: "data", releaseRelevant: true, description: "Schema migration safety guard changes.", legacyMatches: ["migration", "validation"] }),
  Object.freeze({ label: "enum compatibility", parent: "enum value", family: "data", releaseRelevant: true, description: "Enum compatibility changes.", legacyMatches: ["compatibility"] }),
  Object.freeze({ label: "field default", parent: "field rule", family: "data", releaseRelevant: true, description: "Schema field default changes." }),
  Object.freeze({ label: "wire version", parent: "wire format", family: "data", releaseRelevant: true, description: "Wire protocol version changes.", versionBump: "major" })
]);

module.exports = {
  EXTRA_LEAVES
};