import collections
import collections.abc

collections.MutableSequence = collections.abc.MutableSequence
SYSTEM_MESSAGE = None
beam_kwargs = {
    "do_sample": False,
    "top_k": 2,
    "temperature": 1.15,
    "no_repeat_ngram_size": 3,
    "num_beams": 4,
    "early_stopping": True,
}
higher_beams = 64
ai_model_extensions = [
    "safetensors",
    "onnx",
    "pt",
    "pth",
    "h5",
    "keras",
    "pb",
    "tflite",
    "gguf",
    "ckpt",
]
unesco_mapping = {
    "ar": [
        "acm_Arab",
        "acq_Arab",
        "aeb_Arab",
        "ajp_Arab",
        "apc_Arab",
        "arb_Arab",
        "ars_Arab",
        "ary_Arab",
        "arz_Arab",
    ],
    "af": "afr_Latn",
    "ak": ["aka_Latn", "twi_Latn"],
    "am": "amh_Ethi",
    "as": "asm_Beng",
    "ay": "ayr_Latn",
    "az": ["azb_Arab", "azj_Latn"],
    "bm": "bam_Latn",
    "be": "bel_Cyrl",
    "bn": "ben_Beng",
    "bho": "bho_Deva",
    "bs": "bos_Latn",
    "bg": "bul_Cyrl",
    "ca": "cat_Latn",
    "ceb": "ceb_Latn",
    "cs": "ces_Latn",
    "ckb": "ckb_Arab",
    "cy": "cym_Latn",
    "da": "dan_Latn",
    "de": "deu_Latn",
    "el": "ell_Grek",
    "en": "eng_Latn",
    "eo": "epo_Latn",
    "et": "est_Latn",
    "eu": "eus_Latn",
    "ee": "ewe_Latn",
    "fi": "fin_Latn",
    "fr": "fra_Latn",
    "gd": "gla_Latn",
    "ga": "gle_Latn",
    "gl": "glg_Latn",
    "gn": "grn_Latn",
    "gu": "guj_Gujr",
    "ht": "hat_Latn",
    "ha": "hau_Latn",
    "he": "heb_Hebr",
    "iw": "heb_Hebr",
    "hi": "hin_Deva",
    "hr": "hrv_Latn",
    "hu": "hun_Latn",
    "hy": "hye_Armn",
    "ig": "ibo_Latn",
    "ilo": "ilo_Latn",
    "id": "ind_Latn",
    "is": "isl_Latn",
    "it": "ita_Latn",
    "jw": "jav_Latn",
    "ja": "jpn_Jpan",
    "kn": "kan_Knda",
    "ka": "kat_Geor",
    "kk": "kaz_Cyrl",
    "km": "khm_Khmr",
    "rw": "kin_Latn",
    "ky": "kir_Cyrl",
    "ku": "kmr_Latn",
    "ko": "kor_Hang",
    "lo": "lao_Laoo",
    "ln": "lin_Latn",
    "lt": "lit_Latn",
    "lb": "ltz_Latn",
    "lg": "lug_Latn",
    "lus": "lus_Latn",
    "lv": "lvs_Latn",
    "mai": "mai_Deva",
    "ml": "mal_Mlym",
    "mr": "mar_Deva",
    "mk": "mkd_Cyrl",
    "mg": "plt_Latn",
    "mt": "mlt_Latn",
    "mni-mtei": "mni_Beng",
    "mn": "khk_Cyrl",
    "mi": "mri_Latn",
    "my": "mya_Mymr",
    "nl": "nld_Latn",
    "no": ["nno_Latn", "nob_Latn"],
    "ne": "npi_Deva",
    "nso": "nso_Latn",
    "ny": "nya_Latn",
    "om": "gaz_Latn",
    "or": "ory_Orya",
    "pa": "pan_Guru",
    "fa": ["pes_Arab", "prs_Arab"],
    "pl": "pol_Latn",
    "pt": "por_Latn",
    "ps": "pbt_Arab",
    "qu": "quy_Latn",
    "ro": "ron_Latn",
    "ru": "rus_Cyrl",
    "sa": "san_Deva",
    "si": "sin_Sinh",
    "sk": "slk_Latn",
    "sl": "slv_Latn",
    "sm": "smo_Latn",
    "sn": "sna_Latn",
    "sd": "snd_Arab",
    "so": "som_Latn",
    "st": "sot_Latn",
    "es": "spa_Latn",
    "sq": "als_Latn",
    "sr": "srp_Cyrl",
    "su": "sun_Latn",
    "sv": "swe_Latn",
    "sw": "swh_Latn",
    "ta": "tam_Taml",
    "tt": "tat_Cyrl",
    "te": "tel_Telu",
    "tg": "tgk_Cyrl",
    "tl": "tgl_Latn",
    "th": "tha_Thai",
    "ti": "tir_Ethi",
    "ts": "tso_Latn",
    "tr": "tur_Latn",
    "tk": "tuk_Latn",
    "ug": "uig_Arab",
    "uk": "ukr_Cyrl",
    "ur": "urd_Arab",
    "uz": "uzn_Latn",
    "vi": "vie_Latn",
    "xh": "xho_Latn",
    "yi": "ydd_Hebr",
    "yo": "yor_Latn",
    "zh-cn": "zho_Hans",
    "zh-tw": "zho_Hant",
    "ms": "zsm_Latn",
    "zu": "zul_Latn",
}
language_codes = {
    "af": "afrikaans",
    "sq": "albanian",
    "am": "amharic",
    "ar": "arabic",
    "hy": "armenian",
    "as": "assamese",
    "ay": "aymara",
    "az": "azerbaijani",
    "bm": "bambara",
    "eu": "basque",
    "be": "belarusian",
    "bn": "bengali",
    "bho": "bhojpuri",
    "bs": "bosnian",
    "bg": "bulgarian",
    "ca": "catalan",
    "ceb": "cebuano",
    "ny": "chichewa",
    "zh-cn": "chinese (simplified)",
    "zh-tw": "chinese (traditional)",
    "co": "corsican",
    "hr": "croatian",
    "cs": "czech",
    "da": "danish",
    "dv": "dhivehi",
    "doi": "dogri",
    "nl": "dutch",
    "en": "english",
    "eo": "esperanto",
    "et": "estonian",
    "ee": "ewe",
    "tl": "filipino",
    "fi": "finnish",
    "fr": "french",
    "fy": "frisian",
    "gl": "galician",
    "ka": "georgian",
    "de": "german",
    "el": "greek",
    "gn": "guarani",
    "gu": "gujarati",
    "ht": "haitian creole",
    "ha": "hausa",
    "haw": "hawaiian",
    "iw": "hebrew",
    "he": "hebrew",
    "hi": "hindi",
    "hmn": "hmong",
    "hu": "hungarian",
    "is": "icelandic",
    "ig": "igbo",
    "ilo": "ilocano",
    "id": "indonesian",
    "ga": "irish",
    "it": "italian",
    "ja": "japanese",
    "jw": "javanese",
    "kn": "kannada",
    "kk": "kazakh",
    "km": "khmer",
    "rw": "kinyarwanda",
    "gom": "konkani",
    "ko": "korean",
    "kri": "krio",
    "ku": "kurdish (kurmanji)",
    "ckb": "kurdish (sorani)",
    "ky": "kyrgyz",
    "lo": "lao",
    "la": "latin",
    "lv": "latvian",
    "ln": "lingala",
    "lt": "lithuanian",
    "lg": "luganda",
    "lb": "luxembourgish",
    "mk": "macedonian",
    "mai": "maithili",
    "mg": "malagasy",
    "ms": "malay",
    "ml": "malayalam",
    "mt": "maltese",
    "mi": "maori",
    "mr": "marathi",
    "mni-mtei": "meiteilon (manipuri)",
    "lus": "mizo",
    "mn": "mongolian",
    "my": "myanmar",
    "ne": "nepali",
    "no": "norwegian",
    "or": "odia (oriya)",
    "om": "oromo",
    "ps": "pashto",
    "fa": "persian",
    "pl": "polish",
    "pt": "portuguese",
    "pa": "punjabi",
    "qu": "quechua",
    "ro": "romanian",
    "ru": "russian",
    "sm": "samoan",
    "sa": "sanskrit",
    "gd": "scots gaelic",
    "nso": "sepedi",
    "sr": "serbian",
    "st": "sesotho",
    "sn": "shona",
    "sd": "sindhi",
    "si": "sinhala",
    "sk": "slovak",
    "sl": "slovenian",
    "so": "somali",
    "es": "spanish",
    "su": "sundanese",
    "sw": "swahili",
    "sv": "swedish",
    "tg": "tajik",
    "ta": "tamil",
    "tt": "tatar",
    "te": "telugu",
    "th": "thai",
    "ti": "tigrinya",
    "ts": "tsonga",
    "tr": "turkish",
    "tk": "turkmen",
    "ak": "twi",
    "uk": "ukrainian",
    "ur": "urdu",
    "ug": "uyghur",
    "uz": "uzbek",
    "vi": "vietnamese",
    "cy": "welsh",
    "xh": "xhosa",
    "yi": "yiddish",
    "yo": "yoruba",
    "zu": "zulu",
}
FFMPEG_URL = "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip"
tasks = {
    "general-tokenizer": "distilbert-base-uncased",
    "video": "hunyuanvideo-community/HunyuanVideo-I2V",
    "image": "black-forest-labs/FLUX.1-dev",
    "image-spro": "tencent/SRPO",
    "detect": "facebook/detr-resnet-50",
    "answer": "microsoft/Phi-4-multimodal-instruct",
    "summary": "google-t5/t5-large",
    "music": "facebook/musicgen-small",
    "translate": "facebook/nllb-200-3.3B",
    "song": "https://huggingface.co/tencent/SongGeneration/resolve/main/ckpt/songgeneration_base/model.pt",
    "speech-recognition": "openai/whisper-large-v3",
    "audio-classification": "MIT/ast-finetuned-audioset-10-10-0.4593",
}
MODELS = {
    "video": None,
    "image": None,
    "upscale": None,
    "detect": None,
    "answer": None,
    "summary": None,
    "translate": None,
    "music": None,
    "song": None,
    "speech-recognition": None,
    "audio-classification": None,
    "tts": None,
    "stable-whisper": None,
}
TOKENIZERS = {"summary": None, "translate": None, "general-tokenizer": None}
PROCESSORS = {"answer": None, "music": None}
CONFIGS = {"answer": None}
user_agents = {
    "chrome": [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    ],
    "firefox": [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:126.0) Gecko/20100101 Firefox/126.0",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0",
    ],
    "safari": [
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15",
        "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148b Safari/604.1",
        "Mozilla/5.0 (iPad; CPU OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148b Safari/604.1",
    ],
    "egde": [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0",
    ],
    "opera": [
        "Opera/9.80 (Windows NT 6.0) Presto/2.12.388 Version/12.14",
        "Opera/9.80 (Macintosh; Intel Mac OS X 10.6.8; U; en) Presto/2.9.168 Version/11.52",
    ],
    "chrome-mobile": [
        "Mozilla/5.0 (Linux; Android 10; SM-G973F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
        "Mozilla/5.0 (Linux; Android 13; Pixel 7 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
        "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/120.0.6099.119 Mobile/15E148b Safari/604.1",
    ],
    "safari-mobile": [
        "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148b Safari/604.1",
        "Mozilla/5.0 (iPad; CPU OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148b Safari/604.1",
    ],
}
try:
    import madmom

    MADMOM_AVAILABLE = True
except ImportError:
    MADMOM_AVAILABLE = False
STYLES_DB = {
    "Psychedelic Geometry": {
        "tags": ["Abstract", "Trippy", "Geometry"],
        "desc": "Twisting geometric shapes responding to audio",
    },
    "Image Pulse": {
        "tags": ["Simple", "Image", "Beat"],
        "desc": "Background image pulsing to the beat",
    },
    "Spectrum Bars": {
        "tags": ["Classic", "Equalizer", "Retro"],
        "desc": "Classic bottom-up frequency bars",
    },
    "Particle Tunnel": {
        "tags": ["Sci-Fi", "Space", "3D"],
        "desc": "3D particle tunnel accelerating on beats",
    },
    "Glitch Art": {
        "tags": ["Cyberpunk", "Distortion", "Noise"],
        "desc": "Digital distortion and chromatic aberration",
    },
    "Neon City": {
        "tags": ["Cyberpunk", "Synthwave", "Retro"],
        "desc": "Glowing outlines in 80s synthwave style",
    },
    "Liquid Bass": {
        "tags": ["Abstract", "Fluid", "Smooth"],
        "desc": "Fluid motion reacting to low frequencies",
    },
}
iio_formats = ["png", "jpg", "jpeg", "gif", "bmp", "tiff", "tif"]
common_audio_formats = [
    "wav",
    "mp3",
    "flac",
    "aac",
    "ogg",
    "opus",
    "aiff",
    "m4a",
    "wma",
]
_negative_prompt_ = "glamour, makeup, airbrushed, smooth, retouching, polished, perfect, oversaturated, CGI, 3d, vfx, SFX, rendered, painted, unreal, octane, cinematic, bokeh, blurry, cropped, mutated, duplicated"
_positive_prompt_ = "journalism, realism, national geographic, minimalism, rough, grainy, messy, natural, correct structure, correct anatomy"
