import collections
import collections.abc
import re

from definers.catalogs.languages import LANGUAGE_CODES, UNESCO_MAPPING
from definers.catalogs.references import FFMPEG_URL, STYLE_CATALOG, USER_AGENTS
from definers.catalogs.tasks import TASKS
from definers.state import get_default_runtime_collections

RUNTIME_REFERENCES = get_default_runtime_collections()
MODELS = RUNTIME_REFERENCES.models
TOKENIZERS = RUNTIME_REFERENCES.tokenizers
PROCESSORS = RUNTIME_REFERENCES.processors
CONFIGS = RUNTIME_REFERENCES.configs

collections.MutableSequence = collections.abc.MutableSequence
SYSTEM_MESSAGE = None
beam_kwargs = {
    "do_sample": False,
    "top_k": 2,
    "temperature": 1.15,
    "no_repeat_ngram_size": 3,
    "num_beams": 4,
    "early_stopping": True,
}
higher_beams = 64
unesco_mapping = UNESCO_MAPPING

MAX_INPUT_LENGTH = 1024

MAX_CONSECUTIVE_SPACES = 3

language_codes = LANGUAGE_CODES
tasks = TASKS
user_agents = USER_AGENTS
try:
    import madmom

    MADMOM_AVAILABLE = True
except ImportError:
    MADMOM_AVAILABLE = False
STYLES_DB = STYLE_CATALOG
iio_formats = ["png", "jpg", "jpeg", "gif", "bmp", "tiff", "tif"]
common_audio_formats = [
    "wav",
    "mp3",
    "flac",
    "aac",
    "ogg",
    "opus",
    "aiff",
    "m4a",
    "wma",
]

common_video_formats = [
    "mp4",
    "mkv",
    "avi",
    "mov",
    "webm",
    "flv",
    "mpeg",
    "mpg",
    "m4v",
    "3gp",
]
binary_formats = [
    "exe",
    "msi",
    "deb",
    "rpm",
    "dmg",
    "appimage",
    "snap",
    "flatpak",
    "apk",
    "pkg",
    "jar",
    "dll",
    "so",
    "dylib",
    "o",
    "a",
    "class",
    "pyc",
    "pyo",
    "elc",
    "beam",
    "hi",
    "bin",
    "dat",
    "obj",
    "out",
    "com",
    "sys",
    "iso",
    "img",
    "vmdk",
    "vdi",
    "vhd",
    "qcow2",
    "bundle",
    "dsk",
    "vhd",
    "ova",
    "vbox",
    "wasm",
    "wasmlib",
]
common_compressed_formats = [
    "tar.gz",
    "tar.bz2",
    "tar.xz",
    "tar.zst",
    "tar.Z",
    "tar.lz",
    "tar.lzma",
    "tgz",
    "tbz",
    "tbz2",
    "txz",
    "tar",
    "zip",
    "7z",
    "rar",
    "iso",
    "img",
    "cab",
    "gz",
    "bz2",
    "xz",
    "zst",
    "brotli",
    "compress",
    "deflate",
    "lz",
    "lzma",
    "lzh",
]

pkg_file_formats = [
    "whl",
    "egg",
    "tar.gz",
    "tgz",
    "gem",
    "nupkg",
    "jar",
    "apk",
    "deb",
    "rpm",
    "pkg",
    "jar.asc",
    "sig",
    "crate",
    "lock",
    "rlib",
    "rmeta",
    "checksum",
    "nuspec",
    "pom",
    "gradle",
    "npm",
    "package.json",
    "csproj",
    "vbproj",
    "sln",
    "paket",
    "nuget",
]

compiled_code_formats = [
    "adb",
    "ads",
    "ada",
    "asm",
    "cal",
    "c",
    "cc",
    "cpp",
    "cxx",
    "dart",
    "f",
    "f03",
    "f08",
    "f77",
    "f90",
    "f95",
    "for",
    "go",
    "h",
    "hlsl",
    "hh",
    "hpp",
    "hxx",
    "idl",
    "java",
    "kt",
    "kts",
    "m",
    "mm",
    "objc",
    "objc++",
    "rlib",
    "rs",
    "scala",
    "s",
    "S",
    "swift",
    "v",
    "vhdl",
    "vhd",
    "vert",
    "vgsl",
    "wgsl",
]

common_text_formats = [
    "txt",
    "json",
    "yaml",
    "yml",
    "csv",
    "log",
    "tsv",
    "md",
    "markdown",
    "mdx",
    "xml",
    "ini",
    "cfg",
    "conf",
    "html",
    "htm",
    "elm.html",
]

script_formats = [
    "astro",
    "awk",
    "bash",
    "bat",
    "bas",
    "bin",
    "cl",
    "clj",
    "cljs",
    "cljc",
    "cmd",
    "coffee",
    "cmake",
    "cmake.in",
    "css",
    "dart",
    "dockerfile",
    "dtml",
    "el",
    "elm",
    "eex",
    "erlang",
    "ex",
    "exs",
    "fish",
    "gitignore",
    "gradle",
    "groovy",
    "jinja",
    "j2",
    "js",
    "json5",
    "jsx",
    "ksh",
    "less",
    "lisp",
    "lsp",
    "m4",
    "make",
    "makefile",
    "man",
    "mkspec",
    "mo",
    "nim",
    "nimble",
    "pkg",
    "po",
    "properties",
    "ps1",
    "psd1",
    "psm1",
    "psql",
    "py",
    "pyc",
    "pyd",
    "pyo",
    "pyi",
    "r",
    "rake",
    "rb",
    "rst",
    "rs",
    "rmd",
    "scala",
    "sh",
    "sql",
    "sqlx",
    "svelte",
    "swift",
    "tcl",
    "tex",
    "tpl",
    "twig",
    "tsx",
    "vb",
    "vbs",
    "vue",
    "wdl",
    "xsl",
    "xslx",
    "zsh",
]

safe_model_formats = [
    "safetensors",
    "gguf",
    "ggml",
    "lite",
    "tflite",
]

ai_model_formats = [
    *safe_model_formats,
    "pt",
    "pth",
    "onnx",
    "h5",
    "pb",
    "pkl",
    "model",
    "joblib",
    "keras",
    "hdf5",
    "msgpack",
    "protobuf",
    "torchscript",
    "savedmodel",
    "mlmodel",
    "rknn",
    "neuro",
    "ncnn",
    "checkpoint",
    "ckpt",
    "meta",
    "index",
    "weights",
    "embeddings",
    "npy",
    "npz",
    "tensor",
]
SAFE_EXTENSIONS = [
    *iio_formats,
    *common_audio_formats,
    *common_text_formats,
    *common_video_formats,
    *safe_model_formats,
    "data",
    "tmp",
]
KNOWN_EXTENSIONS = [
    *iio_formats,
    *common_audio_formats,
    *common_text_formats,
    *common_video_formats,
    *common_compressed_formats,
    *ai_model_formats,
    *binary_formats,
    *pkg_file_formats,
    *script_formats,
    *compiled_code_formats,
    "data",
    "tmp",
]
general_negative_prompt = "glamour, makeup, airbrushed, smooth, retouching, polished, perfect, oversaturated, CGI, 3d, vfx, SFX, rendered, painted, unreal, octane, cinematic, bokeh, blurry, cropped, mutated, duplicated"
general_positive_prompt = "journalism, realism, national geographic, minimalism, rough, grainy, messy, natural, correct structure, correct anatomy"

MAX_PATTERN_LENGTH = 1000
NESTED_QUANTIFIER_RE = re.compile(r"\([^()+*]*[+*][^()]*\)[+*]")
