from types import MappingProxyType
from typing import Final, TypeAlias

LanguageCatalogEntry: TypeAlias = tuple[str, str]
UnescoCatalogEntry: TypeAlias = tuple[str, str | tuple[str, ...]]

_UNESCO_CORE_GROUPS: Final[tuple[UnescoCatalogEntry, ...]] = (
    (
        "ar",
        (
            "acm_Arab",
            "acq_Arab",
            "aeb_Arab",
            "ajp_Arab",
            "apc_Arab",
            "arb_Arab",
            "ars_Arab",
            "ary_Arab",
            "arz_Arab",
        ),
    ),
    ("af", "afr_Latn"),
    ("ak", ("aka_Latn", "twi_Latn")),
    ("am", "amh_Ethi"),
    ("as", "asm_Beng"),
    ("ay", "ayr_Latn"),
    ("az", ("azb_Arab", "azj_Latn")),
    ("bm", "bam_Latn"),
    ("be", "bel_Cyrl"),
    ("bn", "ben_Beng"),
    ("bho", "bho_Deva"),
    ("bs", "bos_Latn"),
    ("bg", "bul_Cyrl"),
    ("ca", "cat_Latn"),
    ("ceb", "ceb_Latn"),
    ("cs", "ces_Latn"),
    ("ckb", "ckb_Arab"),
    ("cy", "cym_Latn"),
    ("da", "dan_Latn"),
    ("de", "deu_Latn"),
    ("el", "ell_Grek"),
    ("en", "eng_Latn"),
    ("eo", "epo_Latn"),
    ("et", "est_Latn"),
    ("eu", "eus_Latn"),
    ("ee", "ewe_Latn"),
    ("fi", "fin_Latn"),
    ("fr", "fra_Latn"),
    ("gd", "gla_Latn"),
    ("ga", "gle_Latn"),
    ("gl", "glg_Latn"),
    ("gn", "grn_Latn"),
    ("gu", "guj_Gujr"),
    ("ht", "hat_Latn"),
    ("ha", "hau_Latn"),
    ("he", "heb_Hebr"),
    ("iw", "heb_Hebr"),
    ("hi", "hin_Deva"),
    ("hr", "hrv_Latn"),
    ("hu", "hun_Latn"),
)

_UNESCO_EXTENDED_GROUPS: Final[tuple[UnescoCatalogEntry, ...]] = (
    ("hy", "hye_Armn"),
    ("ig", "ibo_Latn"),
    ("ilo", "ilo_Latn"),
    ("id", "ind_Latn"),
    ("is", "isl_Latn"),
    ("it", "ita_Latn"),
    ("jw", "jav_Latn"),
    ("ja", "jpn_Jpan"),
    ("kn", "kan_Knda"),
    ("ka", "kat_Geor"),
    ("kk", "kaz_Cyrl"),
    ("km", "khm_Khmr"),
    ("rw", "kin_Latn"),
    ("ky", "kir_Cyrl"),
    ("ku", "kmr_Latn"),
    ("ko", "kor_Hang"),
    ("lo", "lao_Laoo"),
    ("ln", "lin_Latn"),
    ("lt", "lit_Latn"),
    ("lb", "ltz_Latn"),
    ("lg", "lug_Latn"),
    ("lus", "lus_Latn"),
    ("lv", "lvs_Latn"),
    ("mai", "mai_Deva"),
    ("ml", "mal_Mlym"),
    ("mr", "mar_Deva"),
    ("mk", "mkd_Cyrl"),
    ("mg", "plt_Latn"),
    ("mt", "mlt_Latn"),
    ("mni-mtei", "mni_Beng"),
    ("mn", "khk_Cyrl"),
    ("mi", "mri_Latn"),
    ("my", "mya_Mymr"),
    ("nl", "nld_Latn"),
    ("no", ("nno_Latn", "nob_Latn")),
    ("ne", "npi_Deva"),
    ("nso", "nso_Latn"),
    ("ny", "nya_Latn"),
    ("om", "gaz_Latn"),
    ("or", "ory_Orya"),
)

_UNESCO_REGIONAL_GROUPS: Final[tuple[UnescoCatalogEntry, ...]] = (
    ("pa", "pan_Guru"),
    ("fa", ("pes_Arab", "prs_Arab")),
    ("pl", "pol_Latn"),
    ("pt", "por_Latn"),
    ("ps", "pbt_Arab"),
    ("qu", "quy_Latn"),
    ("ro", "ron_Latn"),
    ("ru", "rus_Cyrl"),
    ("sa", "san_Deva"),
    ("si", "sin_Sinh"),
    ("sk", "slk_Latn"),
    ("sl", "slv_Latn"),
    ("sm", "smo_Latn"),
    ("sn", "sna_Latn"),
    ("sd", "snd_Arab"),
    ("so", "som_Latn"),
    ("st", "sot_Latn"),
    ("es", "spa_Latn"),
    ("sq", "als_Latn"),
    ("sr", "srp_Cyrl"),
    ("su", "sun_Latn"),
    ("sv", "swe_Latn"),
    ("sw", "swh_Latn"),
    ("ta", "tam_Taml"),
    ("tt", "tat_Cyrl"),
    ("te", "tel_Telu"),
    ("tg", "tgk_Cyrl"),
    ("tl", "tgl_Latn"),
    ("th", "tha_Thai"),
    ("ti", "tir_Ethi"),
    ("ts", "tso_Latn"),
    ("tr", "tur_Latn"),
    ("tk", "tuk_Latn"),
    ("ug", "uig_Arab"),
    ("uk", "ukr_Cyrl"),
    ("ur", "urd_Arab"),
    ("uz", "uzn_Latn"),
    ("vi", "vie_Latn"),
    ("xh", "xho_Latn"),
    ("yi", "ydd_Hebr"),
    ("yo", "yor_Latn"),
    ("zh-cn", "zho_Hans"),
    ("zh-tw", "zho_Hant"),
    ("ms", "zsm_Latn"),
    ("zu", "zul_Latn"),
)

_LANGUAGE_CORE_GROUPS: Final[tuple[LanguageCatalogEntry, ...]] = (
    ("af", "afrikaans"),
    ("sq", "albanian"),
    ("am", "amharic"),
    ("ar", "arabic"),
    ("hy", "armenian"),
    ("as", "assamese"),
    ("ay", "aymara"),
    ("az", "azerbaijani"),
    ("bm", "bambara"),
    ("eu", "basque"),
    ("be", "belarusian"),
    ("bn", "bengali"),
    ("bho", "bhojpuri"),
    ("bs", "bosnian"),
    ("bg", "bulgarian"),
    ("ca", "catalan"),
    ("ceb", "cebuano"),
    ("ny", "chichewa"),
    ("zh-cn", "chinese (simplified)"),
    ("zh-tw", "chinese (traditional)"),
    ("co", "corsican"),
    ("hr", "croatian"),
    ("cs", "czech"),
    ("da", "danish"),
    ("dv", "dhivehi"),
    ("doi", "dogri"),
    ("nl", "dutch"),
    ("en", "english"),
    ("eo", "esperanto"),
    ("et", "estonian"),
    ("ee", "ewe"),
    ("tl", "filipino"),
    ("fi", "finnish"),
    ("fr", "french"),
    ("fy", "frisian"),
    ("gl", "galician"),
    ("ka", "georgian"),
    ("de", "german"),
    ("el", "greek"),
    ("gn", "guarani"),
    ("gu", "gujarati"),
)

_LANGUAGE_EXTENDED_GROUPS: Final[tuple[LanguageCatalogEntry, ...]] = (
    ("ht", "haitian creole"),
    ("ha", "hausa"),
    ("haw", "hawaiian"),
    ("iw", "hebrew"),
    ("he", "hebrew"),
    ("hi", "hindi"),
    ("hmn", "hmong"),
    ("hu", "hungarian"),
    ("is", "icelandic"),
    ("ig", "igbo"),
    ("ilo", "ilocano"),
    ("id", "indonesian"),
    ("ga", "irish"),
    ("it", "italian"),
    ("ja", "japanese"),
    ("jw", "javanese"),
    ("kn", "kannada"),
    ("kk", "kazakh"),
    ("km", "khmer"),
    ("rw", "kinyarwanda"),
    ("gom", "konkani"),
    ("ko", "korean"),
    ("kri", "krio"),
    ("ku", "kurdish (kurmanji)"),
    ("ckb", "kurdish (sorani)"),
    ("ky", "kyrgyz"),
    ("lo", "lao"),
    ("la", "latin"),
    ("lv", "latvian"),
    ("ln", "lingala"),
    ("lt", "lithuanian"),
    ("lg", "luganda"),
    ("lb", "luxembourgish"),
    ("mk", "macedonian"),
    ("mai", "maithili"),
    ("mg", "malagasy"),
    ("ms", "malay"),
    ("ml", "malayalam"),
    ("mt", "maltese"),
    ("mi", "maori"),
)

_LANGUAGE_REGIONAL_GROUPS: Final[tuple[LanguageCatalogEntry, ...]] = (
    ("mr", "marathi"),
    ("mni-mtei", "meiteilon (manipuri)"),
    ("lus", "mizo"),
    ("mn", "mongolian"),
    ("my", "myanmar"),
    ("ne", "nepali"),
    ("no", "norwegian"),
    ("or", "odia (oriya)"),
    ("om", "oromo"),
    ("ps", "pashto"),
    ("fa", "persian"),
    ("pl", "polish"),
    ("pt", "portuguese"),
    ("pa", "punjabi"),
    ("qu", "quechua"),
    ("ro", "romanian"),
    ("ru", "russian"),
    ("sm", "samoan"),
    ("sa", "sanskrit"),
    ("gd", "scots gaelic"),
    ("nso", "sepedi"),
    ("sr", "serbian"),
    ("st", "sesotho"),
    ("sn", "shona"),
    ("sd", "sindhi"),
    ("si", "sinhala"),
    ("sk", "slovak"),
    ("sl", "slovenian"),
    ("so", "somali"),
    ("es", "spanish"),
    ("su", "sundanese"),
    ("sw", "swahili"),
    ("sv", "swedish"),
    ("tg", "tajik"),
    ("ta", "tamil"),
    ("tt", "tatar"),
    ("te", "telugu"),
    ("th", "thai"),
    ("ti", "tigrinya"),
    ("ts", "tsonga"),
    ("tr", "turkish"),
    ("tk", "turkmen"),
    ("ak", "twi"),
    ("uk", "ukrainian"),
    ("ur", "urdu"),
    ("ug", "uyghur"),
    ("uz", "uzbek"),
    ("vi", "vietnamese"),
    ("cy", "welsh"),
    ("xh", "xhosa"),
    ("yi", "yiddish"),
    ("yo", "yoruba"),
    ("zu", "zulu"),
)

UNESCO_MAPPING: Final = MappingProxyType(
    {
        key: value
        for key, value in _UNESCO_CORE_GROUPS
        + _UNESCO_EXTENDED_GROUPS
        + _UNESCO_REGIONAL_GROUPS
    }
)

LANGUAGE_CODES: Final = MappingProxyType(
    {
        key: value
        for key, value in _LANGUAGE_CORE_GROUPS
        + _LANGUAGE_EXTENDED_GROUPS
        + _LANGUAGE_REGIONAL_GROUPS
    }
)
