name: Test and Coverage
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Free up disk space on runner
        run: |
          sudo apt-get clean
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/.ghcup

      - name: Cache dependencies
              uses: actions/cache@v4.2.4
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-python

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          wget https://raw.githubusercontent.com/YaronKoresh/definers/refs/heads/main/scripts/setup_cuda.sh
          chmod +x setup_cuda.sh
          ./setup_cuda.sh
          pip install "definers[cuda] @ git+https://github.com/YaronKoresh/definers.git" --extra-index-url https://pypi.nvidia.com

      - name: Run tests with coverage
        run: |
          coverage run --source=definers -m pytest

      - name: Generate Coverage Badge
        uses: tj-actions/coverage-badge-py@v2
        with:
          source: .coverage
          output: coverage.svg
          label: 'Code Coverage'
          
      - name: Commit badge to repository
        run: |
          git config --local user.email "aharonkoresh1@gmail.com"
          git config --local user.name "YaronKoresh"
          git add coverage.svg
          git commit -m "docs: Update coverage badge" || echo "No changes to commit"
          git push
